version: '3'

services:

  frontend:
      build: ./
      image: angular
      container_name: frontend-angular
      volumes:
       - ./src/:/app/src/
       - ./app/node_modules
        #- ./frontend/dist/:/app/dist
      ports:
        - "4200:4200"
      expose:
        - "4200"
      command: "npm start"
