version: '3'

services:

  backend:
    build:
      context: ./backend/
      dockerfile: app.Dockerfile
    image: larang-api
    container_name: backend-laravel
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
    environment:
      PORT: 1337
      DB_HOST: database

  frontend:
      build: ./frontend
      image: angular
      container_name: frontend-angular
      volumes:
       - ./frontend/src/:/app/src/
       - /app/node_modules
        #- ./frontend/dist/:/app/dist
      environment:
        PORT: 4200
      ports:
        - "4200:4200"
      expose:
        - 4200
      command: "npm start"

  redis:
    image: redis:4.0.10
    container_name: larang-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      #- redis-data:/data
      - ./data/redis:/data
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  web:
    build:
      context: ./backend/
      dockerfile: web.Dockerfile
    container_name: larang-web
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
    ports:
      - 1337:80

  database:
    image: mysql:5.7
    container_name: larang-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      #- dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_api
    ports:
      - 3306:3306

#volumes:
#  dbdata:
#  redis-data:
